In [1]:
people = {
    "first":["corey","sophie", "cristian"],
    "last":["schafer","muthoni","rodriguez"],
    "email":["corey@gmail.com","muthoni@gmail.com","rodriguez@gmail.com"]
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

In [4]:
df

      first       last                email
0     corey    schafer      corey@gmail.com
1    sophie    muthoni    muthoni@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com

In [5]:
df['first'] + ' ' + df['last']

0         corey schafer
1        sophie muthoni
2    cristian rodriguez
dtype: str

In [6]:
#add a new column fullname
df['full_name'] = df['first'] + ' ' + df['last']

In [7]:
df

      first       last                email           full_name
0     corey    schafer      corey@gmail.com       corey schafer
1    sophie    muthoni    muthoni@gmail.com      sophie muthoni
2  cristian  rodriguez  rodriguez@gmail.com  cristian rodriguez

In [8]:
df.drop(columns=['first','last'])

                 email           full_name
0      corey@gmail.com       corey schafer
1    muthoni@gmail.com      sophie muthoni
2  rodriguez@gmail.com  cristian rodriguez

In [9]:
df['full_name'].str.split(' ')

0         [corey, schafer]
1        [sophie, muthoni]
2    [cristian, rodriguez]
Name: full_name, dtype: object

In [10]:
#expand argument
df['full_name'].str.split(' ',expand=True)

          0          1
0     corey    schafer
1    sophie    muthoni
2  cristian  rodriguez

In [11]:
#setting 2 columns to the above columns
df[['first','last']] = df['full_name'].str.split(' ',expand=True)

In [12]:
df

      first       last                email           full_name
0     corey    schafer      corey@gmail.com       corey schafer
1    sophie    muthoni    muthoni@gmail.com      sophie muthoni
2  cristian  rodriguez  rodriguez@gmail.com  cristian rodriguez

In [15]:
#adding and remove columns
#adding a single row
# df.append({
#     'first':'tony'
# },ignore_index=True)

AttributeError: 'DataFrame' object has no attribute 'append'

In [16]:
df

      first       last                email           full_name
0     corey    schafer      corey@gmail.com       corey schafer
1    sophie    muthoni    muthoni@gmail.com      sophie muthoni
2  cristian  rodriguez  rodriguez@gmail.com  cristian rodriguez

In [17]:
people = {
    "first":["tony","steve"],
    "last":["stack","rogers"],
    "email":["tony@gmail.com","steve@gmail.com"]
}
df2 = pd.DataFrame(people)

In [19]:
df2

   first    last            email
0   tony   stack   tony@gmail.com
1  steve  rogers  steve@gmail.com

In [20]:
df.append(df2,ignore_index=True)

AttributeError: 'DataFrame' object has no attribute 'append'

In [21]:
df

      first       last                email           full_name
0     corey    schafer      corey@gmail.com       corey schafer
1    sophie    muthoni    muthoni@gmail.com      sophie muthoni
2  cristian  rodriguez  rodriguez@gmail.com  cristian rodriguez

In [22]:
df.drop(index=4)

KeyError: '[4] not found in axis'

In [23]:
df.drop(4,axis=0)

KeyError: '[4] not found in axis'

In [24]:
df

      first       last                email           full_name
0     corey    schafer      corey@gmail.com       corey schafer
1    sophie    muthoni    muthoni@gmail.com      sophie muthoni
2  cristian  rodriguez  rodriguez@gmail.com  cristian rodriguez

In [26]:
#adding a new row
df.loc[3] = ['charlie','simpson','charlie@gmail.com','charlie simpson']

In [27]:
df

      first       last                email           full_name
0     corey    schafer      corey@gmail.com       corey schafer
1    sophie    muthoni    muthoni@gmail.com      sophie muthoni
2  cristian  rodriguez  rodriguez@gmail.com  cristian rodriguez
3   charlie    simpson    charlie@gmail.com     charlie simpson

In [28]:
df.drop(3,axis=0)

      first       last                email           full_name
0     corey    schafer      corey@gmail.com       corey schafer
1    sophie    muthoni    muthoni@gmail.com      sophie muthoni
2  cristian  rodriguez  rodriguez@gmail.com  cristian rodriguez

In [29]:
df

      first       last                email           full_name
0     corey    schafer      corey@gmail.com       corey schafer
1    sophie    muthoni    muthoni@gmail.com      sophie muthoni
2  cristian  rodriguez  rodriguez@gmail.com  cristian rodriguez
3   charlie    simpson    charlie@gmail.com     charlie simpson

In [ ]:
#drop using a condition
df.drop(df['last']== 'simpson')