In [1]:
person = {
    "first":"corey",
    "last":"schafer",
    "email":"corey@gmail.com"
}

In [2]:
person = {
    "first":["corey"],
    "last":["schafer"],
    "email":["corey@gmail.com"]
}

In [3]:
people = {
    "first":["corey","sophie", "cristian"],
    "last":["schafer","muthoni","rodriguez"],
    "email":["corey@gmail.com","muthoni@gmail.com","rodriguez@gmail.com"]
}

In [4]:
#what is a dataframe?
#A DataFrame is a 2-dimensional labeled data structure with Rows(indexed) and 
#Columns(named)

In [5]:
# creating a dataframe from the people object
import pandas as pd

In [6]:
df = pd.DataFrame(people)

In [7]:
df

      first       last                email
0     corey    schafer      corey@gmail.com
1    sophie    muthoni    muthoni@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com

In [8]:
#   (named columns)
#first	last	email 
# 0	corey	schafer	corey@gmail.com   (indexed rows)
# 1	sophie	muthoni	muthoni@gmail.com
# 2	cristian	rodriguez	rodriguez@gmail.com

# 
# 
# 
# 
#

In [9]:
# accessing a specific column in dataframe
df['email']

0        corey@gmail.com
1      muthoni@gmail.com
2    rodriguez@gmail.com
Name: email, dtype: str

In [10]:
type(df['email'])

pandas.Series

In [11]:
#SERIES:
#rows of a single column
#email series:

# 0        corey@gmail.com
# 1      muthoni@gmail.com
# 2    rodriguez@gmail.com
# Name: email, dtype: str

# accessing series as a key
# df['email']

# using dot notation
# df.email
df.email

0        corey@gmail.com
1      muthoni@gmail.com
2    rodriguez@gmail.com
Name: email, dtype: str

In [12]:
#accessing multiple colums
df[['last','email']]

#this is nolonger a series but filtered down dataframe

        last                email
0    schafer      corey@gmail.com
1    muthoni    muthoni@gmail.com
2  rodriguez  rodriguez@gmail.com

In [13]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [14]:
df.iloc[0]
df.iloc[[0,1]]
df.iloc[[0,1],2]

0      corey@gmail.com
1    muthoni@gmail.com
Name: email, dtype: str

In [15]:
#loc (labels)
#the default indexes are our labels:
# label
# 0	schafer	corey@gmail.com
# 1	muthoni	muthoni@gmail.com
# 2	rodriguez	rodriguez@gmail.com
df.loc[0]

first              corey
last             schafer
email    corey@gmail.com
Name: 0, dtype: str

In [16]:
df.loc[[0,1],'email']

0      corey@gmail.com
1    muthoni@gmail.com
Name: email, dtype: str

In [17]:
df.loc[[0,1],['email','last']]

               email     last
0    corey@gmail.com  schafer
1  muthoni@gmail.com  muthoni

first              corey
last             muthoni
email    corey@gmail.com
dtype: str

In [19]:
df.apply(lambda x:x.min())

first              corey
last             muthoni
email    corey@gmail.com
dtype: str