In [1]:
people = {
    "first":["corey","sophie", "cristian","john","jane"],
    "last":["schafer","muthoni","rodriguez","Doe","Doe"],
    "email":["corey@gmail.com","muthoni@gmail.com","rodriguez@gmail.com",
             "johnDoe@gmail.com","janeDoe@gmail.com"]
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

In [4]:
df

      first       last                email
0     corey    schafer      corey@gmail.com
1    sophie    muthoni    muthoni@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com
3      john        Doe    johnDoe@gmail.com
4      jane        Doe    janeDoe@gmail.com

In [5]:
filt_last = (df['last'] == 'Doe') #can put parenthesis just clean code

In [6]:
filt_last

0    False
1    False
2    False
3     True
4     True
Name: last, dtype: bool

In [7]:
df[filt_last]

  first last              email
3  john  Doe  johnDoe@gmail.com
4  jane  Doe  janeDoe@gmail.com

In [8]:
df.loc[filt_last]

  first last              email
3  john  Doe  johnDoe@gmail.com
4  jane  Doe  janeDoe@gmail.com

In [9]:
df.loc[filt_last, 'email']

3    johnDoe@gmail.com
4    janeDoe@gmail.com
Name: email, dtype: str

In [16]:
filtor = (df['first'] == 'john') | (df['last'] == 'Doe')

In [17]:
df.loc[filtor,'email']

3    johnDoe@gmail.com
4    janeDoe@gmail.com
Name: email, dtype: str

In [18]:
filtand = (df['last'] == 'Doe') & (df['first'] == 'jane')

In [19]:
df.loc[filtand,'email']

4    janeDoe@gmail.com
Name: email, dtype: str