In [1]:
people = {
    "first":["corey","sophie", "cristian"],
    "last":["schafer","muthoni","rodriguez"],
    "email":["corey@gmail.com","muthoni@gmail.com","rodriguez@gmail.com"]
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

df

In [4]:
#What is indexing in pandas
df.set_index('email')

                        first       last
email
corey@gmail.com         corey    schafer
muthoni@gmail.com      sophie    muthoni
rodriguez@gmail.com  cristian  rodriguez

In [5]:
df
#index doesnt change the dataframe unless we explicitly tell pandas to do so

      first       last                email
0     corey    schafer      corey@gmail.com
1    sophie    muthoni    muthoni@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com

In [6]:
df.set_index('email', inplace=True)

In [7]:
df

                        first       last
email
corey@gmail.com         corey    schafer
muthoni@gmail.com      sophie    muthoni
rodriguez@gmail.com  cristian  rodriguez

In [8]:
df.index

Index(['corey@gmail.com', 'muthoni@gmail.com', 'rodriguez@gmail.com'], dtype='str', name='email')

In [11]:
#why is this useful (indexing)
#index becomes label when we use loc[]
df.loc['corey@gmail.com']

first      corey
last     schafer
Name: corey@gmail.com, dtype: str

In [12]:
df.loc['corey@gmail.com','last']

'schafer'

In [13]:
#reseting index
df.reset_index(inplace=True)
df

                 email     first       last
0      corey@gmail.com     corey    schafer
1    muthoni@gmail.com    sophie    muthoni
2  rodriguez@gmail.com  cristian  rodriguez