In [1]:
people = {
    "first":["corey","sophie", "cristian"],
    "last":["schafer","muthoni","rodriguez"],
    "email":["corey@gmail.com","muthoni@gmail.com","rodriguez@gmail.com"]
}

In [2]:
import pandas as pd

In [4]:
df = pd.DataFrame(people)

In [5]:
df

      first       last                email
0     corey    schafer      corey@gmail.com
1    sophie    muthoni    muthoni@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com

In [6]:
#sorting by lastname

In [7]:
df.sort_values(by='last')

      first       last                email
1    sophie    muthoni    muthoni@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com
0     corey    schafer      corey@gmail.com

In [9]:
#in descending order
df.sort_values(by='last', ascending=False)

      first       last                email
0     corey    schafer      corey@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com
1    sophie    muthoni    muthoni@gmail.com

In [10]:
#sorting  columns with similar values

df.sort_values(by=['last','first'], ascending=False)

      first       last                email
0     corey    schafer      corey@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com
1    sophie    muthoni    muthoni@gmail.com

In [11]:
df.loc[3] = ['john','Doe','john@gmail.com']

In [12]:
df

      first       last                email
0     corey    schafer      corey@gmail.com
1    sophie    muthoni    muthoni@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com
3      john        Doe       john@gmail.com

In [13]:
df.loc[4] = ['jane','Doe','jane@gmail.com']

In [14]:
df

      first       last                email
0     corey    schafer      corey@gmail.com
1    sophie    muthoni    muthoni@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com
3      john        Doe       john@gmail.com
4      jane        Doe       jane@gmail.com

In [15]:
df.sort_values(by=['last','first'], ascending=False)

      first       last                email
0     corey    schafer      corey@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com
1    sophie    muthoni    muthoni@gmail.com
3      john        Doe       john@gmail.com
4      jane        Doe       jane@gmail.com

In [16]:
df.loc[4] = ['adam','Doe','adam@gmail.com']

In [17]:
df

      first       last                email
0     corey    schafer      corey@gmail.com
1    sophie    muthoni    muthoni@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com
3      john        Doe       john@gmail.com
4      adam        Doe       adam@gmail.com

In [18]:
df.loc[5] = ['jane','Doe','jane@gmail.com']

In [19]:
df

      first       last                email
0     corey    schafer      corey@gmail.com
1    sophie    muthoni    muthoni@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com
3      john        Doe       john@gmail.com
4      adam        Doe       adam@gmail.com
5      jane        Doe       jane@gmail.com

In [20]:
#sorting last names in ascending order while first name in descending order
df.sort_values(by=['last','first'], ascending=[False,True])

      first       last                email
0     corey    schafer      corey@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com
1    sophie    muthoni    muthoni@gmail.com
4      adam        Doe       adam@gmail.com
5      jane        Doe       jane@gmail.com
3      john        Doe       john@gmail.com

In [21]:
#making the sort permanent use inplace=True
df.sort_values(by=['last','first'], ascending=[False,True], inplace=True)

In [22]:
df

      first       last                email
0     corey    schafer      corey@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com
1    sophie    muthoni    muthoni@gmail.com
4      adam        Doe       adam@gmail.com
5      jane        Doe       jane@gmail.com
3      john        Doe       john@gmail.com

In [23]:
df.sort_index()

      first       last                email
0     corey    schafer      corey@gmail.com
1    sophie    muthoni    muthoni@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com
3      john        Doe       john@gmail.com
4      adam        Doe       adam@gmail.com
5      jane        Doe       jane@gmail.com

In [24]:
df

      first       last                email
0     corey    schafer      corey@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com
1    sophie    muthoni    muthoni@gmail.com
4      adam        Doe       adam@gmail.com
5      jane        Doe       jane@gmail.com
3      john        Doe       john@gmail.com

In [25]:
df = df.sort_index()

In [26]:
df

      first       last                email
0     corey    schafer      corey@gmail.com
1    sophie    muthoni    muthoni@gmail.com
2  cristian  rodriguez  rodriguez@gmail.com
3      john        Doe       john@gmail.com
4      adam        Doe       adam@gmail.com
5      jane        Doe       jane@gmail.com

In [28]:
#sorting series
df['last'].sort_values()

3          Doe
4          Doe
5          Doe
1      muthoni
2    rodriguez
0      schafer
Name: last, dtype: str